### PR TITLE
Update IDN Rule index.md - Added Beanshell Mention

### LINKED ISSUE #126: [Feature] Rules documentation should make a notable mention that Rules are written in Java Beanshell
**Is your feature request related to a problem? Please describe.

Rules documentation doesn't make any mention today that Rules are written in Java Beanshell.

**Describe the solution you'd like.** A clear and concise description of what you want to happen.

Rules documentation should make a notable mention that Rules are written in Java Beanshell.

### PR DESCRIPTION
**Pull request by anitarodia**
Fixes #126 
Added Java Beanshell mention in Rule Doc

### CODE REVIEW

**Review by colin-mckibben-sp — CHANGES_REQUESTED** [review]
Can you please make the following changes:

- Move this section to be below the "Overview" section.
- Change the title to "Java Beanshell"
- Remove the phrase "It's worth noting that".  The first sentence should start with "Rules in Identity Now are written..."
- Please provide an appropriate link to the Java Beanshell docs so users can find more information about the language.

**Comment by anitarodia** [comment]
image

Looks good?

**Comment by colin-mckibben-sp** [comment]
Can you share the link you are providing to the docs?  Just want to check which doc site you are referring to.

**Comment by colin-mckibben-sp** [comment]
@tyler-mairose-sp anything else you want to add to this?

**Comment by tyler-mairose-sp** [comment]
> @tyler-mairose-sp anything else you want to add to this?

No, this looks like a good addition to me!

**Review by tyler-mairose-sp — APPROVED** [review]

**Review by colin-mckibben-sp — APPROVED** [review]

**Pull request merged**
