### PR TITLE
Update identity_attribute_rule.md

### PR DESCRIPTION
**Pull request by piyush-khandelwal-sp**

### CODE REVIEW

**Comment by jordan-violet-sp** [comment]
@tyler-mairose-sp review for technical correctness

@james-haytko-sp review writing

**Comment by jordan-violet-sp** [comment]
@piyush-khandelwal-sp please sign the CLA as well so we will be able to merge: https://github.com/sailpoint-oss/developer.sailpoint.com/pull/121#issuecomment-1336764562

**Comment by piyush-khandelwal-sp** [comment]
@jordan-violet-sp this text is literally copied from original guide which was missing.. https://community.sailpoint.com/t5/IdentityNow-Articles/IdentityNow-Rule-Guide-Identity-Attribute-Rule/ta-p/73619

**Comment by jordan-violet-sp** [comment]
> @jordan-violet-sp this text is literally copied from original guide which was missing.. https://community.sailpoint.com/t5/IdentityNow-Articles/IdentityNow-Rule-Guide-Identity-Attribute-Rule/ta-p/73619

That’s awesome, great catch! We’ll review it and get it added asap.

**Review by jordan-violet-sp — APPROVED** [review]

**Comment by jordan-violet-sp** [comment]
Merged! Thanks @piyush-khandelwal-sp for the commit!

**Pull request merged**
